---
- hosts: AnsibleTower
  gather_facts: false
  
  tasks:
    - name: Create Update Log Folder
      win_file:
        path: C:\AnsibleUpdateLog
        state: directory
    
    - name: Copy Update Log File to Machine 
      #THERE MUST BE A BETTER WAY TO DO THIS! Also need to make this idempotent
      win_copy:
        src: UpdateLog.txt # required. Local path to a file to copy to the remote server; can be absolute or relative.,If path is a directory, it is copied (including the source folder name) recursively to C(dest).,If path is a directory and ends with "/", only the inside contents of that directory are copied to the destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied.,If path is a file and dest ends with "\", the file is copied to the folder with the same filename.
        dest: C:\AnsibleUpdateLog\UpdateLog.txt # required. Remote absolute path where the file should be copied to. If src is a directory, this must be a directory too.,Use \ for path separators or \ when in "double quotes".,If C(dest) ends with \ then source or the contents of source will be copied to the directory without renaming.,If C(dest) is a nonexistent path, it will only be created if C(dest) ends with "/" or "\", or C(src) is a directory.,If C(src) and C(dest) are files and if the parent directory of C(dest) doesn't exist, then the task will fail.
      
    - name: Install Latest Security Updates
      # need a way to skip this if update fails
      win_updates:
        log_path: C:\AnsibleUpdateLog\UpdateLog.txt 
        category: DefinitionUpdates 
        state: installed
      notify: Update Complete 

    - meta: flush_handlers # Force Handler to run after updates installed.

    - name: Install chocolatey packages
      win_chocolatey:
        name: "{{ item }}"
        msg: Installing "{{ item }}"
        state: present
      with_items:
        - googlechrome
        - firefox
        - notepadplusplus.install
        - git.install
        - putty.install
          
    - name: Install SysInternals
      win_chocolatey:
        name: sysinternals
        state: present
        params: /InstallDir:C:\SysInternals

    
#    - name: Install Network Policy and Access Server
#      win_feature:
#        name: NPAS
#        state: present
#        include_management_tools: true
#        reboot_required: true
#      register: reboot_required

#    - name: Debug  
#      debug: 
#        msg: "{{ reboot_required }}"

  handlers:
    - name: Update Complete
      win_reboot:

# change hostname
# give a static ip
# copy an NPS config file and import it
# install and anti-virus program
# Turn off automatic updates 

